### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by Orinion** [Orinion/AimTux#1]
- [ ] Draw the Grenade Infos
- [ ] Make a Different Aim mode when close enough
- [ ] Make a Grenade-aimbot in CreateMove.
- [ ] Add a Window/Settings in ImGUI
- [ ] Load Grenade Infos from a config file

**Comment by Orinion** [comment]
- [ ] Different Colors/Color Settings
